### ISSUE TITLE
Control issues 

### ISSUE THREAD

**Issue by kierank01** [SylvainGa/garmin-tesla#4]
Hi,
I'm really have difficulty controlling the widget.
Installed on a forerunner 945.
The only button that works seems to be the (top right) start/stop button, which activates the climate control.
The 3 buttons on the left, seem to control the watch, rather than the widget.
The light button operates the light, long press power menu.
The up button goes up to the next widget, long press goes into the Tesla link menu, which is useful.
The down button goes down to the next widget, long press into music.

I have read the documentation, but it doesn't seem to match what happens on the watch.

**Comment by SylvainGa** [comment]
This has been fixed. Make sure you have the latest update (7.13.4). On a button operated watch, the main view when launched directly from the widgets/apps loop (and not the glance loop) do not have controls over the Up/Down button, as these are used to moved within the widgets/apps loop. To fix it, I had to add bring the main view deeper, hence the extra button press at start (that's the one now where the Up/Down moves you through the loop). That's an unfortunate reality of a button operated watches. On a touch screen, that limitation doesn't exist as the pressing the screen and swiping up/down are two different gesture.
