### ISSUE TITLE
Instinct 2X Support

### ISSUE THREAD

**Issue by n-gineer** [SylvainGa/garmin-tesla#9]
I saw your comments [here](https://www.reddit.com/r/TeslaModel3/comments/qzchi3/for_those_that_wear_a_garmin_watch/) included 64KB memory limit as a constraint. How can I see how much memory this currently uses? Is it the binary from the VS Code Monkey C extension as described [here](https://developer.garmin.com/connect-iq/submit-an-app/)? Noting your comment from the reddit thread, I'm looking to get oriented on how to take your app and pare down for instinct 2X. Please let me know how you'd like to see this implemented (Separate Garmin app, "Tesla Link Light", or similar). And if you have any recommendations for where to start trimming (or what to leave in place), please let me know!

**Comment by SylvainGa** [comment]
Hi, like we discussed by email, unfortunately, this watch has too little memory to run the app.
